language: php

php:
  - '7.3'

before_script:
  - composer install -n

script:
  - php vendor/bin/phpunit --coverage-clover build/coverage/xml tests

after_success:
  - php vendor/bin/codacycoverage clover build/coverage/xml