language: php

php:
  - '7.3'

services:
  - mysql

before_script:
  - composer install -n
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - cp .env.example .env

script:
  - php artisan migrate
  - php vendor/bin/phpunit --coverage-clover build/coverage/xml tests

after_success:
  - php vendor/bin/codacycoverage clover build/coverage/xml